### ISSUE TITLE
gradle cannot find v 1.0.1

### ISSUE THREAD

**Issue by kcrimi** [IFTTT/SparkleMotion#48]

**Comment by lzanita09** [comment]
Are you sure you're using this in your build.gradle file?

```
compile 'com.ifttt:sparklemotion:1.0.1'
```

**Comment by kcrimi** [comment]
Sorry, looks like my project was only using `mavenCentral` for repositories. This could only resolve `v1.0.0` which was confusing. Adding `jcenter` to my repositories in the `build.gradle` file fixed it up. Thanks
