### ISSUE TITLE
[removed]

### ISSUE THREAD

**Issue by PapaCharlie** [IFTTT/SparkleMotion#52]

**Comment by lzanita09** [comment]
@PapaCharlie What is this?

**Comment by PapaCharlie** [comment]
Woah weird, wasn't me. Looks like somebody's running the endpoint tests on the Github channel, and I haven't revoked my token.

**Comment by lzanita09** [comment]
Interesting...

**Comment by PapaCharlie** [comment]
I just revoked everything. Shouldn't happen again! Though it is really really weird. SparkleMotion shouldn't be the test repo

**Comment by lzanita09** [comment]
I'll ask around and see what's happening.

**Comment by PapaCharlie** [comment]
Yeah, please do! Thanks!

**Comment by PapaCharlie** [comment]
^ Lol

**Comment by davoclavo** [comment]
I checked and the test/setup is pointing to  another repo, perhaps there is an instance somewhere with the old setup?

**Comment by PapaCharlie** [comment]
Well yeah, that's what's really weird. Maybe there's a really old version rattling around somewhere? There's an "issues_and_prs" repo which is where the endpoint tests should be pointing. Check the ruby version, maybe I copied it over.

**Comment by davoclavo** [comment]
Yeah, for some reason I thought this was weeks old, but I just realized it was created today.

I checked the prod version and it is pointing to "issues_and_prs". I'll try to dig around.
